### ISSUE TITLE
Trying to contact someone regarding Tiny Core Linux

### ISSUE THREAD

**Issue by dsyer** [clbr/radeontop#101]
I see the owner of this repository (clbr) contributing to Tiny Core Linux (e.g. at https://github.com/tinycorelinux/Core-scripts), so I wonder if he or she can help me to contact someone who can help me to access the community resources at http://tinycorelinux.net/? The wiki seems to be borked and the forum says it sent me an activation code, but I don't see any emails. Please reply here or contact me OOB via contact details in my github profile.

**Comment by clbr** [comment]
The wiki is indeed down, but mails should be going out. Could be something with hotmail side too. I've approved your forum account manually.
