### ISSUE TITLE
Cannot compile the application

### ISSUE THREAD

**Issue by JPyke3** [clbr/radeontop#102]
Hi! Thanks for the great tool!

Unfortunately I can't seem to compile the tool. I get an error related to `drm.h`. The file does exist under `/usr/include/xf86drm.h`. Just for whatever reason I cannot compile the application.

Any help would be appreciated :) 

Error Logs:
```
~/Development/radeontop >>> make                                      ±[master]
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
cc -Os -Wall -Wextra -pthread -Iinclude -ffunction-sections -fdata-sections    -DENABLE_XCB=1  -DENABLE_NLS=1 -s   -c -o auth.o auth.c
In file included from auth.c:18:
/usr/include/xf86drm.h:40:10: fatal error: drm.h: No such file or directory
   40 | #include <drm.h>
      |          ^~~~~~~
compilation terminated.
make: *** [<builtin>: auth.o] Error 1
```

**Comment by clbr** [comment]
You're missing several packages, starting from pkg-config and libdrm-devel, or whatever they're called in your distro. xf86drm.h and drm.h are different files.

**Comment by JPyke3** [comment]
So simple and so embarrassing *facepalm* thanks for that. It's been a long day. Appreciate your response time! Thanks!
