### ISSUE TITLE
Error opening terminal

### ISSUE THREAD

**Issue by dm17** [clbr/radeontop#107]
I'm using the latest version of st (suckless terminal)

```
sudo radeontop
Collecting data, please wait....
Error opening terminal: st-256color.
```

**Comment by clbr** [comment]
This is unrelated to radeontop, and an issue in your terminal's installation. Every colorized ncurses app will hit it.

You have set TERM=st-256color but not installed the st-256color file.

**Comment by dm17** [comment]
Great app, thanks.
