### ISSUE TITLE
Cannot access GPU registers

### ISSUE THREAD

**Issue by physkets** [clbr/radeontop#109]
Using sudo or a root account gives me the same message as when using a non-root account:
```
Cannot access GPU registers, are you root?
```
I'm using an AMD Ryzen 7 PRO 4750U with integrated Radeon Graphics. Is that not supported?

**Comment by clbr** [comment]
Your distro may be blocking the access, as mentioned in the README.

**Comment by clbr** [comment]
That is why root access didn't work, that is. Why the other paths failed, I don't know. If there were no other error messages prior to that, it'd be up to you to find out, you have the hw.

**Comment by physkets** [comment]
I'm using Arch Linux, and installed thus using the build-script in the AUR.

The integrated graphic card is pretty new: Vega 7.

There were no other error messages. How do I find out what the issue is?

**Comment by clbr** [comment]
You'd need to add printfs to track what happened, start in detect.c amdgpu path.

**Comment by physkets** [comment]
Okay, never mind; I was using v1.2, and after building the current git version, it works.
