### ISSUE TITLE
Plans to migrate to sysfs?

### ISSUE THREAD

**Issue by baryluk** [clbr/radeontop#110]
Hi,

I was wondering if it would be possible to integrate metrics reported by radeontop into kernel, and make them be exposed in sysfs.

This way it can be read by other tools easily without root, tools that comes to mind are mangohud, rocm-smi, radeon-profile, and of course radeontop itself, as well in general will make using and collecting these statistic easier from things like shell or python scripts.

**Comment by clbr** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=73047

As you see, the official place is the DRM ioctl, which already works without root in radeontop.

**Comment by baryluk** [comment]
@clbr This is excellent!

I was testing radeontop 1.2 from Debian testing.

I just tested radeontop 1.3 from this repo, and indeed, it works!
