### ISSUE TITLE
translations from https://translations.launchpad.net/radeontop are missing

### ISSUE THREAD

**Issue by rathann** [clbr/radeontop#112]
The [Launchpad translations service](https://translations.launchpad.net/radeontop) contains translations into the following languages: Chinese, Czech, Finnish, French, German, Greek, Russian, Slovenian, Spanish, and Turkish. Both this repository and the official tarballs contain only Russian translation. Please include the translations.

**Comment by clbr** [comment]
Thanks for the reminder, synced both ways. The launchpad bzr automatic import from git was broken years back, turned it back on and it seems to work.
