### ISSUE TITLE
Add CPU usage on top, merge two VRAM entries

### ISSUE THREAD

**Issue by strelec** [clbr/radeontop#12]
First of all, CPU usage is an important information (even if it is not strictly related to GPU). This way you can know what is bottlenecking, CPU or GPU. So it would look like this:
```
                 radeontop , running on RV710, 120 samples/sec                  
                   CPU utilization 8,12% │
                   Graphics pipe  11,67% │    
─────────────────────────────────────────┼──
                    Event Engine   6,67% │  
```

Secondly, there are two lines related to VRAM reporting, which consume most precious vertical space. It looks like this at this moment:

```
                            VRAM  52,12% │                   
                            VRAM    267M │
```
I'd merge it to look like this:
```
                     VRAM (267M)  52,12% │                   
```

**Comment by clbr** [comment]
Fixed by nckx.
