### ISSUE TITLE
Radeontop builds twice when installing

### ISSUE THREAD

**Issue by luyatshimbalanga** [clbr/radeontop#121]
When packaging radeontop for Fedora, the tarball builds twice, first for compilation and second for installation. See the attached 
[build.log](https://github.com/clbr/radeontop/files/6987018/build.log)

**Comment by clbr** [comment]
Cannot reproduce, and the log does not tell me why. Is your build system doing something weird behind the scenes, like clearing the directory between build and install steps?

**Comment by clbr** [comment]
Hm, wait, what tarball? I don't release tarballs since github removed that support several years ago?

Oh, you mean the ones it autogenerates that are git checkouts without the git dir. Yes, it happens for me too there, but those are not meant to be used. Please use a git checkout, or generate a tarball from the git checkout yourself with "make dist".

I'm not sure if I can disable that Releases page.

**Comment by clbr** [comment]
Nope, couldn't find a way to disable it, nor to stop github from autogenerating those from tags.

**Comment by luyatshimbalanga** [comment]
> Cannot reproduce, and the log does not tell me why. Is your build system doing something weird behind the scenes, like clearing the directory between build and install steps?

Not at all. See the attached [radeontop.spec.log](https://github.com/clbr/radeontop/files/6988436/radeontop.spec.log) showing classic make && make install used (make_build is a macro for make and make_install make install in Fedora build system).

**Comment by luyatshimbalanga** [comment]
> Hm, wait, what tarball? I don't release tarballs since github removed that support several years ago?
> 
> Oh, you mean the ones it autogenerates that are git checkouts without the git dir. Yes, it happens for me too there, but those are not meant to be used. Please use a git checkout, or generate a tarball from the git checkout yourself with "make dist".
> 
> I'm not sure if I can disable that Releases page.

Yes the generated tarball. For some reasons, make dist failed
```
 make dist
rm -f *.o radeontop libradeontop_xcb.so
sed -i '/\t\.\/getver.sh/d' Makefile
cd .. && \
ln -s radeontop radeontop-v1.3-4-g1552170 && \
tar -h --numeric-owner --exclude-vcs -cvf - radeontop-v1.3-4-g1552170 | pigz -9 > /tmp/radeontop-v1.3-4-g1552170.tgz && \
rm radeontop-v1.3-4-g1552170
radeontop-v1.3-4-g1552170/
radeontop-v1.3-4-g1552170/COPYING
radeontop-v1.3-4-g1552170/README.md
radeontop-v1.3-4-g1552170/amdgpu.c
radeontop-v1.3-4-g1552170/auth.c
radeontop-v1.3-4-g1552170/auth_xcb.c
radeontop-v1.3-4-g1552170/detect.c
radeontop-v1.3-4-g1552170/dump.c
radeontop-v1.3-4-g1552170/family_str.c
radeontop-v1.3-4-g1552170/familycheck.sh
radeontop-v1.3-4-g1552170/getamdgpuids.sh
radeontop-v1.3-4-g1552170/getver.sh
radeontop-v1.3-4-g1552170/include/
radeontop-v1.3-4-g1552170/include/gettext.h
radeontop-v1.3-4-g1552170/include/r600_pci_ids.h
radeontop-v1.3-4-g1552170/include/radeontop.h
radeontop-v1.3-4-g1552170/include/version.h
radeontop-v1.3-4-g1552170/radeon.c
radeontop-v1.3-4-g1552170/radeontop.1
radeontop-v1.3-4-g1552170/radeontop.asc
radeontop-v1.3-4-g1552170/radeontop.c
radeontop-v1.3-4-g1552170/radeontop.metainfo.xml
radeontop-v1.3-4-g1552170/ticks.c
radeontop-v1.3-4-g1552170/translations/
radeontop-v1.3-4-g1552170/translations/Makefile
radeontop-v1.3-4-g1552170/translations/cs.po
radeontop-v1.3-4-g1552170/translations/de.po
radeontop-v1.3-4-g1552170/translations/el.po
radeontop-v1.3-4-g1552170/translations/es.po
radeontop-v1.3-4-g1552170/translations/fi.po
radeontop-v1.3-4-g1552170/translations/fr.po
radeontop-v1.3-4-g1552170/translations/radeontop.pot
radeontop-v1.3-4-g1552170/translations/ru.po
radeontop-v1.3-4-g1552170/translations/sl.po
radeontop-v1.3-4-g1552170/translations/tr.po
radeontop-v1.3-4-g1552170/translations/zh_CN.po
radeontop-v1.3-4-g1552170/ui.c
radeontop-v1.3-4-g1552170/Makefile
advdef -z4 /tmp/radeontop-v1.3-4-g1552170.tgz
make: advdef: No such file or directory
make: *** [Makefile:136: dist] Error 127
```

**Comment by clbr** [comment]
> make: advdef: No such file or directory

The advdef program is needed for this target.

**Comment by luyatshimbalanga** [comment]
Thanks. I confirm the latest snapshot does not duplicate the builds.
[build.log](https://github.com/clbr/radeontop/files/6990214/build.log)

**Comment by luyatshimbalanga** [comment]
Closing this ticket as the issue is resolved.
