### ISSUE TITLE
Both ubuntu-supplied and built do not support dimgrey_cavefish - also, is this project dead?

### ISSUE THREAD

**Issue by Meganium97** [clbr/radeontop#130]
Self explanatory. I know that a pull was created to support it but I have one and it doesn't show that it's supported, only successfully reporting the memory usage.

**Comment by clbr** [comment]
Git master supports 5 dimgrey cavefish. What's the pci id?

The project is considered done. That's a bit different from dead, it doesn't need any changes other than pci id additions.

**Comment by Meganium97** [comment]
Ah, thanks for the explaination. I also figured it out - my graphics card just runs at zero until something graphical happens. I guess I wasn't really stressing it with only discord open, so having a youtube video open verified that. Thank you.
