### ISSUE TITLE
segmentation fault (core dumped) in tmux

### ISSUE THREAD

**Issue by chromer030** [clbr/radeontop#132]
radeontop is ok in normal terminal window, but in tmux it crashes :

`1]    27176 segmentation fault (core dumped)  radeontop`

**Comment by clbr** [comment]
Do other ncurses apps work in tmux?

**Comment by chromer030** [comment]
Others ncurses apps like : `vim, nano, mc, htop, nload, etc` are working well.

**Comment by chromer030** [comment]
Solved and no SF in latest version of tmux.
