### ISSUE TITLE
Asus G14 2022 dimgrey_cavefish not recognized

### ISSUE THREAD

**Issue by jmcelroy01** [clbr/radeontop#133]
When running ```radeontop -b 3```, the 6700S GPU is identified as "unknown_chip". When running without ```-b 3```, it defaults to the integrated graphics, which is correctly identified as yellow_carp.

**Comment by clbr** [comment]
What's the pci id?

**Comment by jmcelroy01** [comment]
1002:73ef for me. Sounds like this card has a few pci id options though - [https://www.tomshardware.com/news/amd-adds-17-gpu-ids-to-linux](url)

**Comment by danielzgtg** [comment]
This happens to be the same id as my 6650 XT.
