### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by wes1993** [clbr/radeontop#135]
Hello could someone help me with the comping process?
I have Debian 11
![image](https://user-images.githubusercontent.com/52070589/180421118-b4f87de4-8ef2-4fe7-be74-4aeae9e8310d.png)

Best Regards
Stefano

**Comment by danielzgtg** [comment]
1. `sudo apt install pkg-config`
2. `sudo apt install libdrm-dev`
3. Whenever you see an error with `#include <XYZ.h>`, run `sudo apt install libXYZ-dev` or similar

**Comment by wes1993** [comment]
Thanks a lot for you reply :)
