### ISSUE TITLE
inf% Memory Clock and maxed out Shader Clock

### ISSUE THREAD

**Issue by NucleaPeon** [clbr/radeontop#143]
I installed radeontool, both versions 1.4 and then the latest master in git.
I like this tool, though I'm seeing two things that seem off to me.
My Shader Clock is at 100% regardless of what I'm doing; right now I'm at a KDE Plasma desktop with no windows, 1920x1200 res.
My Memory Clock shows inf% and no bar on the right-hand side.

```
0.50G / 0.00G Memory Clock    inf% │
0.60G / 0.60G Shader Clock 100.00% │
```

```
lspci
0000:00:0b.0 PCI bridge: Apple Inc. CPC945 PCIe Bridge
0000:0a:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV620 LE [Radeon HD 3450]
```

```
cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.8"
```

I'm using a PPC64 Big Endian  970MP cpu, though I don't think that would cause the issue. I also restarted and checked to make sure it wasn't a weird fluke, but I still see the same issue.
Any helpful tips to debug the issue? I will do whatever I can to help debug it.

<img width="910" alt="radeontop-ss" src="https://user-images.githubusercontent.com/1475151/199360512-5e970775-dfa9-4c6e-abf3-78d2c0d797ce.png">

**Comment by clbr** [comment]
The low-end GPUs are similar to APUs in that they can't reclock memory.
If your card uses DDR2 or DDR3 - cheaper options than the GDDRs - it's
one of those. APUs can be detected (usually) and that field not shown,
but for fixed-clock ram cards it will look like that.

As for the shader clock, your GPU should be able to reclock that, but
it depends on the kernel settings etc. Running a GL compositor like KDE
may also cause it to stay high. So I'm not sure the measurement is
wrong, it may be right but the system config/runtime keeps it like so.

For how to config that, I don't remember off hand, try searching
phoronix for the r600 reclocking news years ago. I do remember for the
first few years they ran at full clocks, before the dynamic scaling was
introduced, and then it had a few different options to tweak.
