### ISSUE TITLE
two graphics

### ISSUE THREAD

**Issue by taikai-zz** [clbr/radeontop#158]
How to monitor the status of two AMD graphics cards in a single machine?

**Comment by clbr** [comment]
Run two instances of radeontop, pass different -b (bus) to each.

**Comment by taikai-zz** [comment]
rocm-smi   --showbus    


========================= ROCm System Management Interface =========================
==================================== PCI Bus ID ====================================
GPU[0]          : PCI Bus: 0000:00:07.0
GPU[1]          : PCI Bus: 0000:00:08.0
====================================================================================
=============================== End of ROCm SMI Log ================================
radeontop  -b  0000:00:07.0
radeontop  -b  0000:00:08.0
I don't know if what I wrote is correct, but the detection status is still the same graphics card

The current solution is

Radeontop - p/dev/dri/renderD129

Radeontop - p/dev/dri/renderD128
