### ISSUE TITLE
Total VRAM less than expected on Ryzen 5900HS iGPU (Vega)

### ISSUE THREAD

**Issue by qwertychouskie** [clbr/radeontop#163]
```
qwerty@qwerty-asus-g14:~$ sudo dmesg | grep amdgpu | grep memory
[    4.783841] [drm] amdgpu: 512M of VRAM memory ready
[    4.783843] [drm] amdgpu: 7695M of GTT memory ready.
[    5.839234] amdgpu: HMM registered 512MB device memory
```
However, `radeontop` shows `487M` total.  Why is this?

**Comment by Umio-Yasuno** [comment]
That's because the AMDGPU driver returns the usable heap size.

https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/amd/amdgpu/amdgpu_kms.c#L752-L778

**Comment by qwertychouskie** [comment]
Good to know.  Also, just to confirm, is the value returned by the kernel and radeontop in MiB (base 2) or MB (base 10)?

**Comment by Umio-Yasuno** [comment]
MiB

>		float vram = 100.0f * results->vram / vramsize;
>		float vrammb = results->vram / 1024.0f / 1024.0f;
>		float vramsizemb = vramsize / 1024.0f / 1024.0f;

https://github.com/clbr/radeontop/blob/master/ui.c#L155-L157

**Comment by qwertychouskie** [comment]
Awesome, thanks for the insight!
