### ISSUE TITLE
radeontop from multiple GPUs

### ISSUE THREAD

**Issue by brianmatute011** [clbr/radeontop#166]
Hello. My system currently has 6 integrated GPUs. I use radeontop to monitor the resources used. I haven't had any problems with this since `radeontop -b [PCI bus]` but I would like to know if it is possible to monitor the VRAM usage of each of my GPUs in parallel from the same radeontop ui instance? Since I currently have to instantiate `radeontop -b [PCI bus]` 6 times in different sections for each independent bus. 
I'm probably using this incorrectly. Greetings @clb

**Comment by clbr** [comment]
No, one instance can only monitor one GPU. If you want to gather all six to one view, you could use the -d dump mode and some scripting.

**Comment by brianmatute011** [comment]
Excuse me, can I use the `radeontop` source code as a variant and make a small version compiled and optimized for my specific need?

**Comment by clbr** [comment]
It's GPL licensed, so feel free to customize.
