### ISSUE TITLE
AMD Radeon RX 7600 support

### ISSUE THREAD

**Issue by endepointe** [clbr/radeontop#169]
Hi, I get the following error:
Unknown Radeon card. <= R500 won't work, new cards might.

 ```
System:
  Host: pointe Kernel: 6.5.0-1025-oem x86_64 bits: 64 Desktop: Cinnamon 6.0.4
    Distro: Linux Mint 21.3 Virginia
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: TUF GAMING B650-PLUS WIFI v: Rev 1.xx
    serial: <superuser required> UEFI: American Megatrends v: 2613
    date: 04/12/2024
CPU:
  Info: 12-core model: AMD Ryzen 9 7900X bits: 64 type: MT MCP cache:
    L2: 12 MiB
  Speed (MHz): avg: 1172 min/max: 545/5733 cores: 1: 545 2: 545 3: 545
    4: 3592 5: 3423 6: 545 7: 3590 8: 545 9: 545 10: 545 11: 545 12: 3595
    13: 545 14: 545 15: 545 16: 545 17: 545 18: 545 19: 545 20: 545 21: 545
    22: 545 23: 545 24: 3593
Graphics:
  Device-1: AMD driver: amdgpu v: 6.7.0
  Device-2: AMD driver: amdgpu v: 6.7.0
  Device-3: Logitech HD Webcam C615 type: USB
    driver: snd-usb-audio,uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu resolution:
    1: 1920x1080~60Hz 2: 1920x1080~60Hz
  OpenGL: renderer: AMD Radeon RX 7600 (radeonsi navi33 LLVM 17.0.6 DRM
    3.57 6.5.0-1025-oem)
    v: 4.6 Mesa 24.1.0-devel
```

Is 6.5 kernel the issue?

**Comment by clbr** [comment]
Your card, navi33, is too new, and probably won't be supported. This is due to AMD changing directions and no longer providing pci ids. Please look into the alternative programs.

**Comment by endepointe** [comment]
Alright, thank you. 

Radeon-Profile seems to give usage information. 

https://github.com/marazmista/radeon-profile

**Comment by atiq-cs** [comment]
> Your card, navi33, is too new, and probably won't be supported. This is due to AMD changing directions and no longer providing pci ids. Please look into the alternative programs.

What about Radeon 880M? Does it provide PCI Ids?

( I get the same message: unknown card)
