### ISSUE TITLE
Tonga GPU

### ISSUE THREAD

**Issue by qwertzdenek** [clbr/radeontop#17]
Hi,
I have a problem with my new Radeon. VRAM size can't be detected although I added new ID to the headers. My lspci entry is:
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Tonga PRO [Radeon R9 285] [1002:6939]

I don't know nothing about DRM hacking, but I see that *drmCommandWriteRead* commands returns nothing. It starts in method getvram(). I had to change path /dev/dri/card0 to /dev/ati/card0 because I don't have dri directory no more. My DRI is working in other apps.

- ArchLinux with kernel 3.18.5-1-ARCH with nomodeset
- Catalyst Omega (14.501.1003)
- X Server 1.16.3

**Comment by qwertzdenek** [comment]
It just started working when I posted it :). So It's only necessary to add new ID and solve new dri path.

**Comment by qwertzdenek** [comment]
Thats strange, because I getting SIGSEGV when I compile it with included Makefile. I can link it this way:
```Shell
cc  -o radeontop detect.o dump.o family_str.o radeontop.o ticks.o ui.o -Wall -Wextra -DENABLE_NLS=1 -s -pthread -lpciaccess  -ldrm -lncursesw
```
and it works without troubles.

**Comment by clbr** [comment]
I've added support for the fglrx path based on your patch. The access
condition in the original patch was inverted, trying to open each file
only if it did not exist.

Re Tonga, there's much more missing than just one pci id, it's the
entire family with multiple cards. But as long as they're not supported
in libdrm/kernel, I don't want to add the ids either, as I'm bound to
miss ids, as well as I can't be certain the polling address is correct.
So Tonga+ support will come once it's supported in the open drivers. As
of today's git master, it's not yet supported.

For the segfault, if you can replicate with a clean debug build, please
post the valgrind output.

**Comment by qwertzdenek** [comment]
I understand that you can't support it and I added my id at my own risk. I can't reproduce segfault no more on the clean copy so I had to mess something.

**Comment by clbr** [comment]
The kernel pull request has been sent, the polling address has not changed. So Tonga/etc support is just weeks away now, once the amdgpu branch is merged to libdrm.

**Comment by clbr** [comment]
Everyone with Tonga, Topaz, or Carrizo gpu, please test master. Support was added but I have no such hw.

When reported working I can release 0.9.

**Comment by clbr** [comment]
Got confirmation, closing.

**Comment by qwertzdenek** [comment]
Tonga with the fglrx working. I'm not as brave test amdgpu.
