### ISSUE TITLE
No data on X-less Kabini APU (Athlon 5350)

### ISSUE THREAD

**Issue by myxal** [clbr/radeontop#27]
I tried the latest git master version on Ubuntu 14.04 (kernel 3.16, libdrm 2.4.60, fglrx-core 15.200) and I'm getting no data (all zeroes).

Is there a way to find out if this is a kernel/libdrm limitation, or a bug in radeontop?

**Comment by clbr** [comment]
Even on X, if nothing is going on, the GPU will be idle, and all fields
will be zero (except VRAM, but that requires the open driver, you're on
fglrx). Moving the mouse is not enough, I have to move a window around,
scroll, or start a GL load to see numbers.

Did you have a workload going on? Just refreshing the same image at the
console is not enough to create any measurable load.

**Comment by myxal** [comment]
Yeah, forgot to mention -  the load is generated by [Einstein@home's] (https://einstein.phys.uwm.edu/apps.php) opencl_ati

**Comment by clbr** [comment]
Please try the -m (--mem) option. Most of radeontop users are on the open driver, not a lot testing happens on the proprietary one.

**Comment by myxal** [comment]
Sorry for the late reply, the PSU in the machine died literally moments after my last reply :-\

The -m option works. (I was sure I tried it before without success, but it may have been with the old ubuntu-supplied version of radeontoop). Thanks.

I'm seeing ~90% usage on  Graphics Pipe, Texture Addresser and Shader Interpolator, all others are 0.

**Comment by clbr** [comment]
Yes, many of the blocks are graphics-specific, so a CL load wouldn't use them. Closing.
