### ISSUE TITLE
add feature?

### ISSUE THREAD

**Issue by WFV** [clbr/radeontop#28]
Is it possible to get the gpu temperature in radeontop?

**Comment by clbr** [comment]
That comes from lm-sensors, not the GPU registers, so its place is not really there, just like cpu temp, or cpu usage.

**Comment by WFV** [comment]
Capice, thank you.

**Comment by danger89** [comment]
I actually do not agree with this statement sorry.

I think radeontop would be a perfect fit to show AMD Radeon GPU card information. Including (but not limited by) the temperatures.

Why not? This would be very useful.

**Comment by clbr** [comment]
In addition to what was written above, we are now out of screen area. (80x24 default terminal size)

If you're tracking temps, frequencies, etc., that suggests you're likely a gamer and would be better served by a GUI project. There are several that grab the block usages via radeontop, temps and frequencies from elsewhere, and have other features too.

**Comment by danger89** [comment]
I'm not really a gamer. But I was just wondering what the temps are doing on load. I was first checking if my GPU is a bottleneck or the CPU during some stress testing.

I though that temp info could be useful and was requested by others as well (incl. users on stackoverflow). Just saying.

You can make it an optional parameter, so by default you don't show it (doesn't suffer your screen area height).

**Comment by clbr** [comment]
You may be interested that there is now a PR for this. Apparently freebsd doesn't have sensors for gpus, that is an okay reason to add it here. Beware that the patch currently doesn't work though.
