### ISSUE TITLE
Does not dynamically scale when resizing terminal

### ISSUE THREAD

**Issue by vedranmiletic** [clbr/radeontop#30]
Hi,

whether I start radeontop with a narrow or wide terminal, it scales nicely to the terminal width. However, if I resize terminal after starting, radeontop will not resize itself. Also, title bar gets cut off if one shrinks the terminal and enlarges it again.

**Comment by clbr** [comment]
Indeed, there is no code for that. Patches welcome.

**Comment by ismacasti** [comment]
I implemented it on this pull request: #41

**Comment by clbr** [comment]
Fixed in git.
