### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by luyatshimbalanga** [clbr/radeontop#31]
Hello clbr,
Would you clarify which licenses use the following files:
File without license header:
     radeontop-2047d134262b4e9e3514718edc01c27b0ed86352/familycheck.sh
     radeontop-2047d134262b4e9e3514718edc01c27b0ed86352/getamdgpuids.sh
     radeontop-2047d134262b4e9e3514718edc01c27b0ed86352/getver.sh
     radeontop-2047d134262b4e9e3514718edc01c27b0ed86352/include/r600_pci_ids.h

Fedora is currently reviewing radeontop for packaging and the generator provide the above result. [See this review process](https://bugzilla.redhat.com/show_bug.cgi?id=1089962#c21)

**Comment by clbr** [comment]
r600_pci_ids comes from libdrm, and so it's under X11/MIT. The other scripts were written by me, so they are the same as the package, GPLv3.

**Comment by luyatshimbalanga** [comment]
Excellent. Thank you clbr. I am closing this thread.
