### ISSUE TITLE
No VRAM usage on TONGA ( R9 380(x) ) (amdgpu)

### ISSUE THREAD

**Issue by spacekookie** [clbr/radeontop#34]
When I use radeontop with my HD 7770 (GNC 1.0) it can detect the VRAM usage. When I do it on my R9 380X it tells me "Kernel too old for vram" and doesn't.

I am running Ubuntu 16.04 on Kernel 4.7 for both scenarios.
Anything you can do about it?

**Comment by clbr** [comment]
Your newer card uses the amdgpu driver, not radeon. Radeontop has no support for amdgpu, I'm not sure if amdgpu even exposes a VRAM query, and even if it did, I have no such cards to test with.

In short: patches welcome, but not sure it's possible ATM.

**Comment by vedranmiletic** [comment]
Confirmed on Fiji and Polaris.

**Comment by spacekookie** [comment]
I did some investigation into this and it seems that there is a way to get the VRAM usage via Gallium:

```
GALLIUM_HUD="fps,VRAM-usage,GPU-load" glxgears
```

I was also able to run Steam games with this by appending it to the run command

```
GALLIUM_HUD="fps,VRAM-usage,GPU-load" %command%
```

Long story short: amdgpu exposees VRAM usage :) So if Gallium3D can do it, I would hope so can radeontop

**Comment by vedranmiletic** [comment]
@spacekookie looking into it.

**Comment by vedranmiletic** [comment]
I have it working on Tonga here, pull request incoming.

**Comment by spacekookie** [comment]
Hurray :) Awesome! Looking forward to getting the updated version

**Comment by vedranmiletic** [comment]
@spacekookie try #39.

**Comment by clbr** [comment]
Fixed in git.

**Comment by spacekookie** [comment]
@vedranmiletic 

I tested it out. It builds but it doesn't seem to be able to pick up vram usage for me ([link](http://imgur.com/a/p5LGa)).

My system is Ubuntu 16.04 with Kernel 4.8-rc1 and I own an R9 380X (which is Tonga). Do you know if there is something else I need to enable to make this work? :/

**Comment by vedranmiletic** [comment]
Did you enable the amdgpu option in the Makefile?

**Comment by spacekookie** [comment]
Ah nvm...I didn't lok at the Makefile. It works now. Awesome :) <3 Thanks
