### ISSUE TITLE
make install uses wrong libdir

### ISSUE THREAD

**Issue by luyatshimbalanga** [clbr/radeontop#37]
Hello clbr,
Makefile uses the wrong lib on this line
	$(INSTALL) -D -m755 $(xcblib) $(DESTDIR)/$(PREFIX)/lib/$(xcblib)
$(LIBDIR) should be used instead when it comes to install on x86
-64 architecture.

**Comment by clbr** [comment]
LIBDIR indirection added in git.

Note that hard-coding lib64 for x86_64 would be wrong, there are many x86_64 systems that do not use lib64.
