### ISSUE TITLE
Tag new version so distros can update

### ISSUE THREAD

**Issue by rlanting** [clbr/radeontop#43]
I tried the version that is in debian and it doesn't support getting info from my RX 480. After compiling master from here, it worked fine. I contacted the debian maintainer and he said:

> Could you ask upstream to tag a new stable version? Debian usually does not
ship git snapshots for packages (with some exceptions).

It would be nice if you could do this before the fifth of february since debian testing will go into full freeze then and getting this in the new stable would be very nice.

Thanks!

**Comment by clbr** [comment]
Declared 1.0. Closing this.
