### ISSUE TITLE
Small support request

### ISSUE THREAD

**Issue by franglais125** [clbr/radeontop#51]
Hi,

I'm working on adding support for GPU loads for a Gnome Shell extension (https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/386).

Since I don't own a Radeon GPU, I can't test the tool. I was wondering if you could provide me with a way of getting the information needed in a succinct CLI way. I need: the GPU load, the vRAM used, and total vRAM.

Dummy example command:
```
radeontop | grep load
radeontop | grep vRAM
```

Thanks a lot for your time!
Fran

**Comment by clbr** [comment]
Use the dump option.

```
radeontop --help

        RadeonTop for R600 and above.

        Usage: /usr/sbin/radeontop [-ch] [-b bus] [-d file] [-l limit] [-t ticks]

-b --bus 3              Pick card from this PCI bus
-c --color              Enable colors
-d --dump file          Dump data to this file, - for stdout
-l --limit 3            Quit after dumping N lines, default forever
-t --ticks 50           Samples per second (default 120)

-h --help               Show this help
-v --version            Show the version
```

So "radeontop -d -" to output to a pipe continuously, or if you want one-shot, add "-l 1".

Sample line:
```
1502903295.84311: gpu 0.00%, ee 0.00%, vgt 0.00%, ta 0.00%, sx 0.00%, sh 0.00%, spi 0.00%, sc 0.00%, pa 0.00%, db 0.00%, cb 0.00%, vram 30.01% 153.66mb
```

**Comment by clbr** [comment]
For total VRAM, you need to get that some other way.

**Comment by franglais125** [comment]
Thanks a lot! That's exactly what I was looking for.

As for the total VRAM, can I do `153.66 / 30.01%` to get the total?

**Comment by 9898287** [comment]
```
# radeontop -d - -l 1
Dumping to -, line limit 1.
1502903993.303070: gpu 0.83%, ee 0.00%, vgt 0.00%, ta 0.00%, sx 0.00%, sh 0.00%, spi 0.00%, sc 0.83%, pa 0.00%, db 0.00%, cb 0.83%, vram 4.95% 201.15mb
, gtt 0.12% 4.80mb
```

**Comment by franglais125** [comment]
@9898287 , so in your exampe, the total VRAM is `4.80mb / 0.12% = 4000mb` ? I'm asking just to be sure.

Thanks a lot for the quick support!

**Comment by 9898287** [comment]
Yes, that's correct. Also,
```
$ echo $(dmesg | grep -o -P -i "(?<=vram:).*(?=M 0x)")$" Mb"
4096 Mb
```

**Comment by franglais125** [comment]
Thanks again! Cheers.

**Comment by franglais125** [comment]
It seems that root privileges are required to run `radeontop`. Any way around that?

**Comment by clbr** [comment]
Root rights are not required if your kernel is new enough, libdrm is new enough, and your user has access to the DRM node. If you tried to run radeontop without a Radeon card, it would fail to find one in DRM, and assume it needed the root path - even if your system otherwise was set up for non-root access.
