### ISSUE TITLE
How is the value of Graphics pipe calculated?

### ISSUE THREAD

**Issue by shzcore** [clbr/radeontop#52]
How is the value of Graphics pipe calculated?
also
The value is too high to represent what is wrong with the system?

Figure:
![note_attach](https://user-images.githubusercontent.com/19245404/29697908-897b23f4-8984-11e7-8d9c-6318543b18ad.jpg)

**Comment by clbr** [comment]
Like all the others, it's a direct status bit in the register. It means "GPU has any activity going".

In your image, either the GPU is hung, or you're trying to run a computing workload that's too large for your VRAM (mining cryptocurrency?). A normal game would be more spread over, and rarely use any block fully.

**Comment by shzcore** [comment]
Graphics pipe This is the call to the amdgpu interface or other ways？

**Comment by clbr** [comment]
> Graphics pipe This is the call to the amdgpu interface or other ways？
Sorry, I don't understand?

**Comment by shzcore** [comment]
In other words ,"Graphics pipe" and "VRAM" state is synchronized? Why VRAM will be reduced but Graphics pipe has been very high.

What is the relationship between "Graphics pipe" and "VRAM"?

**Comment by clbr** [comment]
There is no direct relationship? A gpu-using program can use 100% of the gpu while using little VRAM, and the opposite can also be true, a program can use all VRAM without using gpu.

**Comment by shzcore** [comment]
Okay, I understand now, thanks
