### ISSUE TITLE
No output stats from AMD rx 560 gpus.

### ISSUE THREAD

**Issue by deevolutionism** [clbr/radeontop#53]
I just get the message "unknown Radeon card".

is it technically possible for this program to monitor my rx 560s?

**Comment by clbr** [comment]
Please post your pci id. (lspci -vnn will show it)

**Comment by deevolutionism** [comment]
pci id: 67FF and I am using the amdgpu driver on ubuntu 16.04LTS.

**Comment by clbr** [comment]
That card is supported since the "Add support for Polaris 11 and
Polaris 10" commit in 2016. Are you using an old version, or perhaps
one compiled without amdgpu support?

**Comment by deevolutionism** [comment]
I installed using the apt-get package manager. I assume amdgpu is not by default enabled when installing with this method? How might I compile and enable amdgpu support myself? My knowledge of gcc / cmake / compiling c programs is fairly limited... Thanks!

**Comment by clbr** [comment]
Looks like only artful/17.10 has a recent enough radeontop. Maybe you
can ask the packager for an update for 16.04?

To compile with amdgpu support, run "make amdgpu=1". I don't use
Ubuntu, but I think you can install the dependencies first with
something like "apt-get build-depends radeontop".

**Comment by deevolutionism** [comment]
I can't find the packagers email address / contact info on launchpad...
I just downloaded the source from github, placed it in my documents folder and had to install a couple dependencies in order to get it to compile...
`sudo apt-get install libpciaccess-dev libncurses-dev`
`make amdgpu=1`
`sudo ./radeontop`

it runs!

**Comment by MrAbaddon** [comment]
Hi,
I have an Asus Radeon RX560 O2GB and it does not show temperature. Only memory usage. I can only see the temperature using sensors.

**Comment by clbr** [comment]
Radeontop does not support temperature, on purpose.

**Comment by clbr** [comment]
The original issue was fixed with an update, closing.
