### ISSUE TITLE
No GPU info for RX480

### ISSUE THREAD

**Issue by evg-tyurin** [clbr/radeontop#54]
I have RX480. I've started from clean Ubuntu 16.04 and installed some software packages for GPU computations from this [manual](https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-install-basic.md)

Then I've installed Radeontop 0.9-1build1 by "apt install". Radeontop writes

Kernel too old for VRAM reporting.
Unknown Radeon card. <= R500 won't work, new cards might.
Collecting data, please wait....

then shows all zeros.

**Comment by clbr** [comment]
RX480 is Polaris 10. Polaris 10 support was added in 1.0. Closing.

**Comment by evg-tyurin** [comment]
How to get 1.0?

**Comment by evg-tyurin** [comment]
If I `make` the latest version I have

Package pciaccess was not found in the pkg-config search path.
Perhaps you should add the directory containing `pciaccess.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pciaccess' found
Package libdrm was not found in the pkg-config search path.
Perhaps you should add the directory containing `libdrm.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libdrm' found
Package xcb-dri2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcb-dri2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xcb-dri2' found
cc -Os -Wall -Wextra -pthread -Iinclude -ffunction-sections -fdata-sections    -DENABLE_XCB=1 -D_GNU_SOURCE -DENABLE_NLS=1 -s   -c -o detect.o detect.c
In file included from detect.c:17:0:
include/radeontop.h:20:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from detect.c:17:0:
include/radeontop.h:36:21: fatal error: xf86drm.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'detect.o' failed
make: *** [detect.o] Error 1

**Comment by clbr** [comment]
Please ask at the Ubuntu forums or IRC, they're in a better position to
help.
