### ISSUE TITLE
Vega Support

### ISSUE THREAD

**Issue by stephen-smith** [clbr/radeontop#57]
Installed a VEGA Frontier Edition today.  Randeontop seems to have stopped working.

```
Failed to open DRM node, no VRAM support.
Unknown Radeon card. <= R500 won't work, new cards might.
```

Any information I can provide to ease adding support?

**Comment by clbr** [comment]
Is your card's pci id 1002:6863? That should already be supported in radeontop git (lspci -vnn will tell you the id). If it's that one, or other one present in the include/r600_pci_ids.h file, then please update your radeontop.

There's a separate issue on new cards on Ubuntu and some other distros, where the root path is not allowed by their kernel config, but the DRM amdgpu path in radeontop is not yet integrated (there's an open pull request, but it had some issues and nobody is working on it - myself I don't have any amdgpu cards).

**Comment by stephen-smith** [comment]
This is me:

```
43:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:6863] (prog-if 00 [VGA controller])
```

So, yeah, looks like I might just need a radeontop upgrade.

**Comment by stephen-smith** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894054

Please tag a new release.

**Comment by clbr** [comment]
Done.
