### ISSUE TITLE
Package does not build cleanly on git clone

### ISSUE THREAD

**Issue by cdplayer** [clbr/radeontop#58]
**$ make**
./getver.sh
Package pciaccess was not found in the pkg-config search path.
Perhaps you should add the directory containing `pciaccess.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pciaccess' found
cc -Os -Wall -Wextra -pthread -Iinclude -ffunction-sections -fdata-sections  -I/usr/include/libdrm  -DENABLE_XCB=1 -D_GNU_SOURCE -DENABLE_NLS=1 -s   -c -o detect.o detect.c
In file included from detect.c:17:0:
include/radeontop.h:20:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
detect.c:18:23: fatal error: pciaccess.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'detect.o' failed
make: *** [detect.o] Error 1

**can deb files for this be made?**

**Comment by clbr** [comment]
You are missing dependencies, at least libpciaccess. Radeontop is packaged in Debian and Ubuntu, so you can download debs there.

**Comment by cdplayer** [comment]
Doh! Thanks, it works fine now.
