### ISSUE TITLE
suggestion - Add screenshots

### ISSUE THREAD

**Issue by C0rn3j** [clbr/radeontop#60]
Screenshots in the README.md would be a good addition imo

**Comment by clbr** [comment]
Please send a pull request.

**Comment by Bengt** [comment]
ASCIInema is full of glitches:

https://asciinema.org/a/iACHEUAZYWvd7R0FQt2QtBlD0

But here is a screenshot of RadeonTop:

![Screenshot from 2019-10-19 01-34-53](https://user-images.githubusercontent.com/11575/67134148-da74d880-f210-11e9-984e-b697c3056c00.png)

**Comment by Bengt** [comment]
... and a bit wider:

![Screenshot from 2019-10-19 01-34-50_cut](https://user-images.githubusercontent.com/11575/67134324-fdec5300-f211-11e9-8597-394d9c062fe7.png)
