### ISSUE TITLE
Show PCI bus on data dump

### ISSUE THREAD

**Issue by grische** [clbr/radeontop#63]
Would it be possible to add the bus id on the dump output? For example, something like:

```
1529693401.34: bus 0a, gpu 0.00%, ee 0.00%, vgt 0.00%, ta 0.00%, sx 0.00%, sh 0.00%, spi 0.00%, sc 0.00%, pa 0.00%, db 0.00%, cb 0.00%, vram 0.04% 2.06mb, gtt 0.04% 2.56mb
```

How could this be implemented? Would you extend `struct bits_t`, so data and bus_id are closely related, so you have a chance for future multi-gpu support?

**Comment by clbr** [comment]
Yes, but this should be quite a simple patch. Would you like to try?
