### ISSUE TITLE
no VRAM support for Wayland

### ISSUE THREAD

**Issue by EUA** [clbr/radeontop#72]
Using Arch Linux x86_64

With "Gnome with Xorg" login, everything is fine and working.

But If I chose "Gnome" which uses Wayland, 

```
[death@Ryzen ~]$ sudo radeontop
[sudo] password for death: 
Failed to open DRM node, no VRAM support.
Collecting data, please wait....
[death@Ryzen ~]$ 

```

**Comment by clbr** [comment]
Try to find why opening it failed (add printfs to the path in detect.c). I don't use Wayland myself, but there shouldn't be anything Wayland-specific.

**Comment by Hello71** [comment]
```
stat("/dev/dri", {st_mode=S_IFDIR|0755, st_size=100, ...}) = 0
stat("/dev/dri/card0", {st_mode=S_IFCHR|0660, st_rdev=makedev(226, 0), ...}) = 0
openat(AT_FDCWD, "/dev/dri/card0", O_RDWR|O_CLOEXEC) = 4
ioctl(4, DRM_IOCTL_SET_VERSION, 0x7ffe605d5110) = -1 EACCES (Permission denied)
ioctl(4, DRM_IOCTL_SET_VERSION, 0x7ffe605d5110) = -1 EACCES (Permission denied)
ioctl(4, DRM_IOCTL_GET_UNIQUE, 0x7ffe605d5100) = 0
ioctl(4, DRM_IOCTL_GET_UNIQUE, 0x7ffe605d5100) = 0
close(4)                                = 0
```

**Comment by Hello71** [comment]
duplicate of #48

**Comment by clbr** [comment]
No, not a dup. That was about the path not being found. Your log shows you don't have permissions to open the path. Grant yourself permissions.

**Comment by Hello71** [comment]
you can clearly see the open succeeded. it is not allowed to set the version because it is not the master.

**Comment by Hello71** [comment]
I scanned through #48 and the error messages are the same as mine. for example it says

```
drmOpenDevice: node name is /dev/dri/card0
drmOpenDevice: open result is 4, (OK)
drmOpenByBusid: drmOpenMinor returns 4
drmOpenByBusid: Interface 1.4 failed, trying 1.1
drmOpenByBusid: drmGetBusid reports 
```

it finds and opens it fine, but it is not allowed to actually use it. (very confusing sentence but hopefully it makes sense)

**Comment by clbr** [comment]
Hm. If the debug prints match, then your case is likely the same. I would still be wary of marking this as a dup, since OP did not mention what card he was using, only that just Wayland failed.

If you have time to dig into this, please try to find why it fails for you, as detailed in #48.

**Comment by myfreeweb** [comment]
Using Wayland on FreeBSD here, `drmOpen` fails in the same way, the workaround from https://github.com/clbr/radeontop/issues/48#issuecomment-355855140 (manual opening) fixes that problem

**Comment by WeaponMan** [comment]
The package on AUR is old, so I tried the -git one and VRM reporting works with it. just fyi

**Comment by EUA** [comment]
Yup. It's working right now!
Thanks.
