### ISSUE TITLE
Can't find any Radeon - Wimbledon XT [Radeon HD 7970M]

### ISSUE THREAD

**Issue by PsySc0rpi0n** [clbr/radeontop#74]
Running radeontop with root privileges forcing AMD/ATI card to be used with:

`sudo DRI_PRIME=1 radeontop`

 I get a "Can't find Radeon cards" error message.

`lspci` shows
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Wimbledon XT [Radeon HD 7970M] (rev ff)

`uname -r` shows
4.9.0-7-amd64

`uname -a` shows
Linux ............ 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux

Any other needed info will be provided if needed!

**Comment by clbr** [comment]
Can you paste the "lspci -vmmnn" output for it?

**Comment by clbr** [comment]
No reply, closing.
