### ISSUE TITLE
question: which metric shows H264 decoding?

### ISSUE THREAD

**Issue by markmal** [clbr/radeontop#96]
which metric shows H264 decoding?

**Comment by clbr** [comment]
None, UVD (decode) and VCE (encode) usage is not currently tracked. They
are possible to track, just not implemented yet.

If your gpu is not doing anything else, then the total usage is the
same as h264 usage.

**Comment by markmal** [comment]
Great, thanks!
if it is not too hard, could you add UVD/VCE to new version?

**Comment by clbr** [comment]
Please see the existing issues about it (#29 etc). I don't have any hw with VCE, and while I do have cards with UVD, I'm not too interested in that.

**Comment by trek00** [comment]
you can try [that version](https://github.com/trek00/radeontop/tree/drm5) with UVD and VCE support

**Comment by markmal** [comment]
cibr thanks!
Hi trek00. Thanks! I've compiled it. It runs. But I do not see UVD. which metric to look?

**Comment by trek00** [comment]
you should see an entry called Unified Video Decoder

if not, you should get an error message or, with some devices/kernel
versions, you may need to run it as root adding to the command line the
option --mem

hope this can help you, anyway what GPU model and kernel version do you
have? you can check with:

lspci -nn | grep VGA; uname -r

ciao!

**Comment by markmal** [comment]
There is no entry called Unified Video Decoder, with or without --mem
Here is text output
```
radeontop-1.2$ sudo ./radeontop --mem -d -
Forcing the /dev/mem path.
Dumping to -, until termination.
1575468860.361103: bus 00, gpu 10.00%, ee 10.00%, vgt 0.00%, ta 7.50%, sx 9.17%, sh 9.17%, spi 9.17%, sc 9.17%, pa 0.00%, db 9.17%, cb 10.00%, vram 58.31% 223.91mb, gtt 14.32% 146.29mb

radeontop-1.2$ lspci -nn | grep VGA; uname -r
00:01.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Wrestler [Radeon HD 6310] [1002:9802]
5.0.0-36-generic
```

**Comment by trek00** [comment]
it should run fine with your card

please double check to have cloned the correct branch:

git clone --branch drm5 https://github.com/trek00/radeontop.git

then compile and check the version:

cd radeontop && make && ./radeontop --version

it should be print:

RadeonTop v1.2-38-gf4fee3c

thank you for testing and sorry for the inconvenience
ciao!

**Comment by markmal** [comment]
Yes, this helped! 
It shows Unified Video Decoder now.

previously I've downloaded release 1.2 looks like it did not have the feature.

**Comment by userofryzen** [comment]
> it should run fine with your card please double check to have cloned the correct branch: git clone --branch drm5 https://github.com/trek00/radeontop.git then compile and check the version: cd radeontop && make && ./radeontop --version it should be print: RadeonTop v1.2-38-gf4fee3c thank you for testing and sorry for the inconvenience ciao!

radeontop --mem -b 05:00.0 
Failed to get UVD usage: error 14 (Dirección incorrecta)
Failed to get VCE usage: error 14 (Dirección incorrecta)
Forcing the /dev/mem path.
Collecting data, please wait....
picasso apu

**Comment by hedgepigdaniel** [comment]
I've tried applying this patch https://github.com/clbr/radeontop/pull/93/commits/5df288ccb5f6231706d280dedb3a23985dbfb5e8 on the current master, but it doesn't work. I see the "Failed to get UVD usage" without `--mem`, with with `--mem` it appears but the value is locked to 100%.

I'm using a 5600XT.

**Comment by thetick1234567890** [comment]
Can this patch 5df288c please be added to the next release as I think some new users of Firefox hardware acceleration like me would like to see UVD / VCE usage?   

So in case anyone does not know Firefox added hardware acceleration recently ( though need Beta 81 )! I have a decade old laptop with AMD Palm Bobcat APU (Radeon HD 6250)  that I can NOW watch hardware accelerated HD YouTube videos full screen without lost frames.  That is absolutely amazing new life for this decade old 1Gz (Dual Core)) laptop!

**Comment by dubigrasu** [comment]
Can confirm that the mentioned fork works very well (for me), both UVC&VCE.

**Comment by thetick1234567890** [comment]
I compiled trek00 drm5 branch awhile back and it works great showing UVD percentage with Firefox using r600 driver streaming H264 files.

@clbr do you plan any new builds?  I'm sure I'm not the only one here questioning your devotion to this code base.  It has been over 9 months and no new builds with the UVD/VCE support.  There are many new Vega and Navi GPUs along with many old UVD / VCE Radeons that now have beautifully working h264 hardware acceleration on Firefox.  Many of us are highly interested in the UVD and VCE usage stats even though clearly are not.  And your completely false "If your gpu is not doing anything else, then the total usage is the same as h264 usage" is actually quite upsetting coming from a developer who should know better.   Your statement is clearly proved false from the UVD stats I've seen on my machine. 

Sorry if I'm I a bit harsh but if you are too busy to do a simple merge , tag, compile and test every six months then please pass ownership of radeontop to someone who does have the time.  Thanks.

**Comment by clbr** [comment]
If you prefer a fork, then use the fork.

**Comment by userofryzen** [comment]
I think fork is not the way to go. 

May be if you can say what's needed on the code side here to be merged, the creator of the code can do it in some time. 
And may be a flag to enable it or disable it in compilation or execution time would be better than not having this  support at all in time..
I am interested in the code but I understand that is YOUR code and you want some exact level of quality or features in some part, so, please, take our concerns too, I know that you have 0 obligations. It's more a favour to all of us.

**Comment by thetick1234567890** [comment]
Not that my opinion matters more than anyone else I agree 100% with userofryzen.  I really don't like forks and it's clbr's code.  In this case it's very easy to build radeontop and I'm OK with that.   And thanks to clbr and all the contributors including  trek00 and cnamburu for their past efforts.

**Comment by myfreeweb** [comment]
> I see the "Failed to get UVD usage" without --mem, with with --mem it appears but the value is locked to 100%.

Same on VEGA10 here

**Comment by TomZanna** [comment]
Any news? Both #45 and #93 are outdated and a simple rebase is not feasible.

**Comment by TomZanna** [comment]
Any news? Both #45 and #93 aren't working on my Renoir CPU and a simple rebase is not feasible.

It would be really useful to verify the functioning of the graphics acceleration on Firefox!

**Comment by vgarleanu** [comment]
Any update on this? Being able to see encode/decode stats would be a killer feature.

**Comment by Habraten** [comment]
Hardware
HP ProLiant ML310e Gen8 v2
AMD RX 550 2Gb
ILO on board video

Software
CentOS 7.9 (kernel3.10.0-1160.83.1.el7.x86_64)
Radeon™ Software for Linux® version 18.50 installed only AMDGPU All-Open

Primary ILO on board video Secondary AMD RX 550

RadeonTop 1.4

I'm trying to figure out how to determine the appearance of the load on the GPU from hardware acceleration VAAPI (decoding) of IP camera sreams.

radeontop shows activity and changes are only in these sensors. the remaining indicators are at zero

`132М / 2043М VRAM   6,45% │   
38M / 3065M GTT   1,25% │ 
0,30G / 1,75G Memory Clock  17,14% 
0,58G / 1,18G Shader Clock  48,09%`

`radeontop -m ` show same list

does the change in these indicators mean that GPU decoding video?

**Comment by clbr** [comment]
> does the change in these indicators mean that GPU decoding video?

No, it's not enough to say that for sure. It could be video decoding or
any other activity.

Your card's pci id should be present, so not sure why things are at
zero. I guess the header says POLARIS12 and not UNKNOWN_CARD?
