### ISSUE TITLE
Any plan to create an API so other projects can FFI from it?

### ISSUE THREAD

**Issue by 98982872** [clbr/radeontop#97]
I'm interested in writing something like MSI afterburner HUD. It'd be real nice if radeontop had provided some kind of a single header API so I could FFI from it instead of talking through stdout (which adds a little bit of latency too).

**Comment by clbr** [comment]
No plans for such. It's not a simple matter, libraries using threads
occasionally cause conflicts in the apps using them, especially if the
app is not native but using some sort of a runtime (java/c#/whatever),
as you mention FFI.

There's not a great demand either, and no need to change radeontop's
config dynamically. It would make the querying slightly nicer yes, but
if you need low latency on your side with stdout, you can have a thread
read it.
